// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateAuthorInput represents a mutation input for creating authors.
type CreateAuthorInput struct {
	Name    string
	Email   string
	BookIDs []int
}

// Mutate applies the CreateAuthorInput on the AuthorMutation builder.
func (i *CreateAuthorInput) Mutate(m *AuthorMutation) {
	m.SetName(i.Name)
	m.SetEmail(i.Email)
	if v := i.BookIDs; len(v) > 0 {
		m.AddBookIDs(v...)
	}
}

// SetInput applies the change-set in the CreateAuthorInput on the AuthorCreate builder.
func (c *AuthorCreate) SetInput(i CreateAuthorInput) *AuthorCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateAuthorInput represents a mutation input for updating authors.
type UpdateAuthorInput struct {
	Name          *string
	Email         *string
	ClearBooks    bool
	AddBookIDs    []int
	RemoveBookIDs []int
}

// Mutate applies the UpdateAuthorInput on the AuthorMutation builder.
func (i *UpdateAuthorInput) Mutate(m *AuthorMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Email; v != nil {
		m.SetEmail(*v)
	}
	if i.ClearBooks {
		m.ClearBooks()
	}
	if v := i.AddBookIDs; len(v) > 0 {
		m.AddBookIDs(v...)
	}
	if v := i.RemoveBookIDs; len(v) > 0 {
		m.RemoveBookIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateAuthorInput on the AuthorUpdate builder.
func (c *AuthorUpdate) SetInput(i UpdateAuthorInput) *AuthorUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateAuthorInput on the AuthorUpdateOne builder.
func (c *AuthorUpdateOne) SetInput(i UpdateAuthorInput) *AuthorUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateBookInput represents a mutation input for creating books.
type CreateBookInput struct {
	Title           string
	Genre           string
	PublicationDate string
	Isbn            string
	CreatedAt       *time.Time
	AuthorID        *int
}

// Mutate applies the CreateBookInput on the BookMutation builder.
func (i *CreateBookInput) Mutate(m *BookMutation) {
	m.SetTitle(i.Title)
	m.SetGenre(i.Genre)
	m.SetPublicationDate(i.PublicationDate)
	m.SetIsbn(i.Isbn)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.AuthorID; v != nil {
		m.SetAuthorID(*v)
	}
}

// SetInput applies the change-set in the CreateBookInput on the BookCreate builder.
func (c *BookCreate) SetInput(i CreateBookInput) *BookCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateBookInput represents a mutation input for updating books.
type UpdateBookInput struct {
	Title           *string
	Genre           *string
	PublicationDate *string
	Isbn            *string
	CreatedAt       *time.Time
	ClearAuthor     bool
	AuthorID        *int
}

// Mutate applies the UpdateBookInput on the BookMutation builder.
func (i *UpdateBookInput) Mutate(m *BookMutation) {
	if v := i.Title; v != nil {
		m.SetTitle(*v)
	}
	if v := i.Genre; v != nil {
		m.SetGenre(*v)
	}
	if v := i.PublicationDate; v != nil {
		m.SetPublicationDate(*v)
	}
	if v := i.Isbn; v != nil {
		m.SetIsbn(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if i.ClearAuthor {
		m.ClearAuthor()
	}
	if v := i.AuthorID; v != nil {
		m.SetAuthorID(*v)
	}
}

// SetInput applies the change-set in the UpdateBookInput on the BookUpdate builder.
func (c *BookUpdate) SetInput(i UpdateBookInput) *BookUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateBookInput on the BookUpdateOne builder.
func (c *BookUpdateOne) SetInput(i UpdateBookInput) *BookUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
